### PR TITLE
Add support of sending log to elasticsearch

### PR DESCRIPTION
**Pull request by huikang**
- Updated README

### CODE REVIEW

**Comment by huikang** [comment]
@periklis , this PR implements sending log to a local elasticsearch (`localhost:9200`). If we need to allow non-localhost, I will add some environment variable like username, password, etc.

Please let me know if this is the right direction to go. Thanks.

**Review by periklis — APPROVED** [review]
This looks really awesome. Outstanding work! Thank you!

**Comment by periklis** [comment]
> @periklis , this PR implements sending log to a local elasticsearch (`localhost:9200`). If we need to allow non-localhost, I will add some environment variable like username, password, etc.
> 
> Please let me know if this is the right direction to go. Thanks.

Yes the server URL should be configurable. For example the logger can be deployed as a pod into the k8s cluster and from there on connects to an in-cluster Elasticsearch, e.g. `elasticsearch.openshift-logging.svc.:9200`.

**Comment by huikang** [comment]
@periklis , a new commit is checked in. I would quash them if it looks good to you. Thanks.

**Review by periklis — COMMENTED** [review]
LGTM

**Review by periklis — APPROVED** [review]

**Pull request merged**
